services:
  default_container:
    build:
      context: ./default_container
    container_name: default_container
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - omechu-net

  auth_api_blue:
    image: ${DOCKER_IMAGE_AUTH}:${AUTH_BLUE_TAG}
    container_name: auth_api_blue
    restart: unless-stopped
    networks:
      - omechu-net
    env_file:
      - ./auth/.env.production
    depends_on:
      - omechu_db

  auth_api_green:
    image: ${DOCKER_IMAGE_AUTH}:${AUTH_GREEN_TAG}
    container_name: auth_api_green
    restart: unless-stopped
    networks:
      - omechu-net
    env_file:
      - ./auth/.env.production
    depends_on:
      - omechu_db

  menu_api_blue:
    image: ${DOCKER_IMAGE_MENU}:${MENU_BLUE_TAG}
    container_name: menu_api_blue
    restart: unless-stopped
    networks:
      - omechu-net
    env_file:
      - ./menu/.env.production
    depends_on:
      - omechu_db

  menu_api_green:
    image: ${DOCKER_IMAGE_MENU}:${MENU_GREEN_TAG}
    container_name: menu_api_green
    restart: unless-stopped
    networks:
      - omechu-net
    env_file:
      - ./menu/.env.production
    depends_on:
      - omechu_db

  user_api_blue:
    image: ${DOCKER_IMAGE_USER}:${USER_BLUE_TAG}
    container_name: user_api_blue
    restart: unless-stopped
    networks:
      - omechu-net
    env_file:
      - ./user/.env.production
    depends_on:
      - omechu_db

  user_api_green:
    image: ${DOCKER_IMAGE_USER}:${USER_GREEN_TAG}
    container_name: user_api_green
    restart: unless-stopped
    networks:
      - omechu-net
    env_file:
      - ./user/.env.production
    depends_on:
      - omechu_db

  omechu_db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=omechu1234
      - MYSQL_DATABASE=omechu_db
      - MYSQL_USER=omechu1234
      - MYSQL_PASSWORD=omechu1234
    container_name: omechu_db
    restart: unless-stopped
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - omechu-net
    volumes:
      - omechu_db_data:/var/lib/mysql
    ports:
      - "3306:3306"

networks:
  omechu-net:
    external: true

volumes:
  omechu_db_data:
